apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend todo-ui
spec:
  replicas: 10
  selector:
    matchLabels:
      app: frontend todo-ui
  template:
    metadata:
      labels:
        app: frontend todo-ui
    spec:
      containers:
      - name: frontend todo-ui
        image: ritesh.azurecr.io/fromtendui:v1
        ports:
        - containerPort: 80
